// Base de datos simulada con 15 empresas
export const contractorsDB = [
    {
        id_contratista: 1,
        rfc: "CON850215ABC",
        razon_social: "Constructora Moderna S.A. de C.V.",
        nombre_comercial: "ConModerna",
        semaforo: "excelente",
        puntaje_total: 95.5,
        estatus_catalogo: "AC",
        tiempo_experiencia: 25,
        proyectos_completados: 145,
        monto_total_ejecutado: 2500000000,
        capacidad_contratacion: 500000000,
        especialidades: ["Edificación", "Urbanización", "Carreteras"],
        fecha_ultima_evaluacion: "2024-11-15",
        calificacion_financiera: "AA",
        sanciones_activas: 0,
        personal_activo: 320,
        maquinaria_operativa: 85
    },
    {
        id_contratista: 2,
        rfc: "ING920803XYZ",
        razon_social: "Ingeniería y Construcciones del Sur S.A.",
        nombre_comercial: "IngSur",
        semaforo: "buena",
        puntaje_total: 85.2,
        estatus_catalogo: "AC",
        tiempo_experiencia: 18,
        proyectos_completados: 98,
        monto_total_ejecutado: 1200000000,
        capacidad_contratacion: 250000000,
        especialidades: ["Obras Hidráulicas", "Puentes"],
        fecha_ultima_evaluacion: "2024-10-22",
        calificacion_financiera: "A",
        sanciones_activas: 0,
        personal_activo: 180,
        maquinaria_operativa: 45
    },
    {
        id_contratista: 3,
        rfc: "EDI780512MNO",
        razon_social: "Edificaciones Integrales del Norte S.C.",
        nombre_comercial: "EdiNorte",
        semaforo: "excelente",
        puntaje_total: 92.8,
        estatus_catalogo: "AC",
        tiempo_experiencia: 30,
        proyectos_completados: 210,
        monto_total_ejecutado: 3100000000,
        capacidad_contratacion: 600000000,
        especialidades: ["Edificación", "Obras Eléctricas", "Telecomunicaciones"],
        fecha_ultima_evaluacion: "2024-11-20",
        calificacion_financiera: "AA",
        sanciones_activas: 0,
        personal_activo: 425,
        maquinaria_operativa: 110
    },
    {
        id_contratista: 4,
        rfc: "URB990125PQR",
        razon_social: "Urbanizaciones y Vialidades S.A. de C.V.",
        nombre_comercial: "UrbaVial",
        semaforo: "mediana",
        puntaje_total: 74.5,
        estatus_catalogo: "AC",
        tiempo_experiencia: 12,
        proyectos_completados: 56,
        monto_total_ejecutado: 680000000,
        capacidad_contratacion: 120000000,
        especialidades: ["Carreteras", "Urbanización"],
        fecha_ultima_evaluacion: "2024-09-10",
        calificacion_financiera: "B",
        sanciones_activas: 1,
        personal_activo: 95,
        maquinaria_operativa: 28
    },
    {
        id_contratista: 5,
        rfc: "HID820918STU",
        razon_social: "Hidráulica Especializada S.A.",
        nombre_comercial: "HidroEsp",
        semaforo: "buena",
        puntaje_total: 88.7,
        estatus_catalogo: "AC",
        tiempo_experiencia: 22,
        proyectos_completados: 134,
        monto_total_ejecutado: 1850000000,
        capacidad_contratacion: 380000000,
        especialidades: ["Obras Hidráulicas", "Obras Ambientales"],
        fecha_ultima_evaluacion: "2024-11-05",
        calificacion_financiera: "A",
        sanciones_activas: 0,
        personal_activo: 245,
        maquinaria_operativa: 62
    },
    {
        id_contratista: 6,
        rfc: "PUE750630VWX",
        razon_social: "Puentes y Estructuras Metálicas S.C.",
        nombre_comercial: "PuentEst",
        semaforo: "excelente",
        puntaje_total: 93.2,
        estatus_catalogo: "AC",
        tiempo_experiencia: 35,
        proyectos_completados: 87,
        monto_total_ejecutado: 2800000000,
        capacidad_contratacion: 550000000,
        especialidades: ["Puentes", "Edificación"],
        fecha_ultima_evaluacion: "2024-11-18",
        calificacion_financiera: "AA",
        sanciones_activas: 0,
        personal_activo: 310,
        maquinaria_operativa: 72
    },
    {
        id_contratista: 7,
        rfc: "OBR010420DEF",
        razon_social: "Obras Civiles y Desarrollos S.A. de C.V.",
        nombre_comercial: "ObraCivil",
        semaforo: "mediana",
        puntaje_total: 71.3,
        estatus_catalogo: "AC",
        tiempo_experiencia: 8,
        proyectos_completados: 42,
        monto_total_ejecutado: 450000000,
        capacidad_contratacion: 85000000,
        especialidades: ["Edificación", "Urbanización"],
        fecha_ultima_evaluacion: "2024-08-30",
        calificacion_financiera: "B",
        sanciones_activas: 0,
        personal_activo: 68,
        maquinaria_operativa: 19
    },
    {
        id_contratista: 8,
        rfc: "TUN881203GHI",
        razon_social: "Túneles y Obras Subterráneas S.A.",
        nombre_comercial: "TunelPro",
        semaforo: "buena",
        puntaje_total: 86.9,
        estatus_catalogo: "AC",
        tiempo_experiencia: 20,
        proyectos_completados: 28,
        monto_total_ejecutado: 1950000000,
        capacidad_contratacion: 420000000,
        especialidades: ["Túneles", "Obras Hidráulicas"],
        fecha_ultima_evaluacion: "2024-10-15",
        calificacion_financiera: "A",
        sanciones_activas: 0,
        personal_activo: 195,
        maquinaria_operativa: 58
    },
    {
        id_contratista: 9,
        rfc: "ELE960715JKL",
        razon_social: "Electrificación Industrial S.C.",
        nombre_comercial: "ElecInd",
        semaforo: "mala",
        puntaje_total: 62.1,
        estatus_catalogo: "SU",
        tiempo_experiencia: 15,
        proyectos_completados: 73,
        monto_total_ejecutado: 520000000,
        capacidad_contratacion: 65000000,
        especialidades: ["Obras Eléctricas"],
        fecha_ultima_evaluacion: "2024-07-20",
        calificacion_financiera: "C",
        sanciones_activas: 2,
        personal_activo: 52,
        maquinaria_operativa: 15
    },
    {
        id_contratista: 10,
        rfc: "CAR830925NOP",
        razon_social: "Carreteras y Pavimentos del Centro S.A.",
        nombre_comercial: "CarrePav",
        semaforo: "buena",
        puntaje_total: 84.6,
        estatus_catalogo: "AC",
        tiempo_experiencia: 19,
        proyectos_completados: 112,
        monto_total_ejecutado: 1450000000,
        capacidad_contratacion: 295000000,
        especialidades: ["Carreteras", "Urbanización"],
        fecha_ultima_evaluacion: "2024-11-08",
        calificacion_financiera: "A",
        sanciones_activas: 0,
        personal_activo: 215,
        maquinaria_operativa: 68
    },
    {
        id_contratista: 11,
        rfc: "AMB020308QRS",
        razon_social: "Ambiental y Sustentabilidad S.A. de C.V.",
        nombre_comercial: "EcoObra",
        semaforo: "mediana",
        puntaje_total: 76.8,
        estatus_catalogo: "AC",
        tiempo_experiencia: 10,
        proyectos_completados: 65,
        monto_total_ejecutado: 780000000,
        capacidad_contratacion: 145000000,
        especialidades: ["Obras Ambientales", "Urbanización"],
        fecha_ultima_evaluacion: "2024-09-25",
        calificacion_financiera: "B",
        sanciones_activas: 0,
        personal_activo: 102,
        maquinaria_operativa: 31
    },
    {
        id_contratista: 12,
        rfc: "MEC790502TUV",
        razon_social: "Instalaciones Mecánicas Profesionales S.C.",
        nombre_comercial: "MecaPro",
        semaforo: "excelente",
        puntaje_total: 91.4,
        estatus_catalogo: "AC",
        tiempo_experiencia: 28,
        proyectos_completados: 156,
        monto_total_ejecutado: 2200000000,
        capacidad_contratacion: 480000000,
        especialidades: ["Instalaciones Mecánicas", "Edificación"],
        fecha_ultima_evaluacion: "2024-11-12",
        calificacion_financiera: "AA",
        sanciones_activas: 0,
        personal_activo: 278,
        maquinaria_operativa: 95
    },
    {
        id_contratista: 13,
        rfc: "TEL970618WXY",
        razon_social: "Telecomunicaciones y Redes S.A.",
        nombre_comercial: "TeleRed",
        semaforo: "buena",
        puntaje_total: 82.3,
        estatus_catalogo: "AC",
        tiempo_experiencia: 16,
        proyectos_completados: 189,
        monto_total_ejecutado: 980000000,
        capacidad_contratacion: 185000000,
        especialidades: ["Telecomunicaciones", "Obras Eléctricas"],
        fecha_ultima_evaluacion: "2024-10-28",
        calificacion_financiera: "A",
        sanciones_activas: 0,
        personal_activo: 156,
        maquinaria_operativa: 42
    },
    {
        id_contratista: 14,
        rfc: "DES910810ZAB",
        razon_social: "Desarrollos Inmobiliarios y Construcción S.A.",
        nombre_comercial: "DesCon",
        semaforo: "mala",
        puntaje_total: 58.7,
        estatus_catalogo: "SU",
        tiempo_experiencia: 11,
        proyectos_completados: 38,
        monto_total_ejecutado: 390000000,
        capacidad_contratacion: 55000000,
        especialidades: ["Edificación"],
        fecha_ultima_evaluacion: "2024-06-15",
        calificacion_financiera: "C",
        sanciones_activas: 3,
        personal_activo: 45,
        maquinaria_operativa: 12
    },
    {
        id_contratista: 15,
        rfc: "INF860422CDE",
        razon_social: "Infraestructura Total S.A. de C.V.",
        nombre_comercial: "InfraTotal",
        semaforo: "excelente",
        puntaje_total: 94.1,
        estatus_catalogo: "AC",
        tiempo_experiencia: 27,
        proyectos_completados: 178,
        monto_total_ejecutado: 3500000000,
        capacidad_contratacion: 650000000,
        especialidades: ["Carreteras", "Puentes", "Túneles", "Urbanización"],
        fecha_ultima_evaluacion: "2024-11-22",
        calificacion_financiera: "AA",
        sanciones_activas: 0,
        personal_activo: 485,
        maquinaria_operativa: 128
    }
];